### ISSUE TITLE
Can change pomodoro time background in mode line?

### ISSUE THREAD

**Issue by hello-code** [baudtack/pomodoro.el#22]
After add `(pomodoro-add-to-mode-line)` ,the time appears in mode line .Can I change the time background color?
Thanks!

**Comment by baudtack** [comment]
I don't understand what you're asking. Are you asking for me to add the ability to change the background color? Or are you asking if i'll merge that change?

**Comment by hello-code** [comment]
Yes,you are right!
How to change the background color?

**Comment by baudtack** [comment]
changing background color is an emacs problem outside of the scope of this project.

**Comment by hello-code** [comment]
Thank you!
