### ISSUE TITLE
why the "w"

### ISSUE THREAD

**Issue by pprw** [baudtack/pomodoro.el#24]
Just wondering why the "w" before the time. Is there a special meaning?

**Comment by ljos** [comment]
It signifies that you are in a work cycle as apposed to a break cycle, which is signaled with a b in front. If you want to change or remove the text in front of the time you can edit the `pomodoro-work-cycle` and `pomodoro-break-cycle` variables.

**Comment by pprw** [comment]
ok I've found out: "work"
